In [2]:
### GENERATE
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
TSKS33 Load data for hands-on session 5

Erik G. Larsson 2020
"""

import sys
import snap
import numpy
sys.path.append("/courses/TSKS33/ht2023/common-functions")
from save_Gephi_gexf import saveGephi_gexf
from save_Gephi_gexf import saveGephi_gexf_twocolors
from gen_stochblock import gen_stoch_block_2comm



### GENERATE

#G1=gen_stoch_block_2comm(700,300,3.0/700,3.0/300,0.1/(700+300))
G1=gen_stoch_block_2comm(700,300,10.0/700,10.0/300,0.3/(700+300))
G=snap.GetMxScc(G1)
snap.SaveEdgeList(G, "SB-small-network.txt")

G1=gen_stoch_block_2comm(10000,5000,3.0/10000,3.0/5000,0.1/(10000+5000))
G=snap.GetMxScc(G1)
snap.SaveEdgeList(G, "SB-large-network.txt")


### LOAD FROM FILES

G = snap.LoadEdgeList(snap.PUNGraph, "test-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "test-network.mat")

G = snap.LoadEdgeList(snap.PUNGraph, "karate-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "karate-network.mat")

G = snap.LoadEdgeList(snap.PUNGraph, "SB-small-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "SB-small-network.mat")

G = snap.LoadEdgeList(snap.PUNGraph, "SB-large-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "SB-large-network.mat")

#G1=gen_stoch_block_2comm(700,300,3.0/700,3.0/300,0.1/(700+300))
G1=gen_stoch_block_2comm(700,300,10.0/700,10.0/300,0.3/(700+300))
G=snap.GetMxScc(G1)
snap.SaveEdgeList(G, "SB-small-network.txt")

G1=gen_stoch_block_2comm(10000,5000,3.0/10000,3.0/5000,0.1/(10000+5000))
G=snap.GetMxScc(G1)
snap.SaveEdgeList(G, "SB-large-network.txt")


### LOAD FROM FILES

G = snap.LoadEdgeList(snap.PUNGraph, "test-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "test-network.mat")

#G = snap.LoadEdgeList(snap.PUNGraph, "karate-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "karate-network.mat")

#G = snap.LoadEdgeList(snap.PUNGraph, "SB-small-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "SB-small-network.mat")

#G = snap.LoadEdgeList(snap.PUNGraph, "SB-large-network.txt", 0, 1)
#snap.SaveMatlabSparseMtx(G, "SB-large-network.mat")


KeyboardInterrupt: 

In [144]:
G = snap.LoadEdgeList(snap.PUNGraph, "test-network.txt", 0, 1)

num_nodes = G.GetNodes()
num_edges = G.GetEdges()
import scipy.sparse as sp
import numpy as np
print(G)

def create_sparse_matrix(snapGraph: snap.PUNGraph):
    rows = []
    cols = []
    data = []
    
    for edge in G.Edges():
        rows.append(edge.GetSrcNId()-1)
        cols.append(edge.GetDstNId()-1)
        data.append(1) 
    coo_matrix = sp.coo_matrix((data, (rows, cols)), shape=(num_nodes, num_nodes))
    return coo_matrix

def getA(snapGraph: snap.PUNGraph):
    A = np.zeros((num_nodes, num_nodes))
    for edge in snapGraph.Edges():
        A[edge.GetSrcNId()-1][edge.GetDstNId()-1] = 1
    return A
    
def getZ(sparse_matrix: sp.coo_matrix):
    sub_matrix = np.ones((num_nodes, num_nodes))/(2*num_edges)
    result_matrix = sp.coo_matrix(sparse_matrix.toarray()-sub_matrix)
    return result_matrix

#m = create_sparse_matrix(G)


#Z = getZ(m).toarray()
A = getA(G)
print(A)

<snap.PUNGraph; proxy of <Swig Object of type 'PUNGraph *' at 0x7f59ecc16240> >
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


In [154]:


sub_mat = np.ones((num_nodes, num_nodes))/(2*num_edges)
print(sub_mat)
def find_dominant_eigenvector(A):
    x  = np.random.rand(num_nodes)
    k = np.ones((1, num_nodes))
    #x /= np.linalg.norm(x)
    eig_values = []
    for i in range(250):
        x = A@x-sub_mat@x
        x /= np.linalg.norm(x)
        eig = x.transpose()@(A@x-sub_mat@x)
        eig_values.append(eig)

    return x, eig_values

def find_eigenvector_corresponding_to_largest_eigen_value():
    pass
x, eig_values = find_dominant_eigenvector(A)
print(x, max(eig_values), min(eig_values))

[[0.08333333 0.08333333 0.08333333 0.08333333 0.08333333 0.08333333]
 [0.08333333 0.08333333 0.08333333 0.08333333 0.08333333 0.08333333]
 [0.08333333 0.08333333 0.08333333 0.08333333 0.08333333 0.08333333]
 [0.08333333 0.08333333 0.08333333 0.08333333 0.08333333 0.08333333]
 [0.08333333 0.08333333 0.08333333 0.08333333 0.08333333 0.08333333]
 [0.08333333 0.08333333 0.08333333 0.08333333 0.08333333 0.08333333]]
[ 0.54492461  0.76052028 -0.1167145   0.30893557 -0.04450099 -0.1167145 ] 0.40684568707214114 0.030061103540466514
