In [41]:
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg
from matplotlib import pyplot as plt

filename = "frena297"
nr_users = 2000
nr_movies = 1500

def load_data(name):
    data = np.genfromtxt(name,delimiter=',',dtype=int)
    data[:,0:2] -= 1
    return data

def getA(data):
    nr_ratings = len(data)

    r = np.concatenate((np.arange(nr_ratings,dtype=int), np.arange(nr_ratings,dtype=int)))
    c = np.concatenate((data[:,0], data[:,1]+nr_users))
    d = np.ones((2*nr_ratings,))

    A = sp.csr_matrix((d,(r,c)),shape=(nr_ratings,nr_users+nr_movies))

    return A

training_data = load_data(filename+'.training')
test_data = load_data(filename+'.test')
print(training_data)

[[  55    0    1]
 [  57    0    5]
 [  70    0    3]
 ...
 [1935 1499    3]
 [1964 1499    1]
 [1988 1499    4]]


In [71]:
u = training_data[:,0]
m = training_data[:,1]
r = training_data[:,2]

r_average = r.sum()/r.size



In [ ]:
test = list(set(zip(u, r)))
print(len(u))
test.sort()
print(test)
userRatings = {}

for user, rating in test:
    if(rating!= None):
        if(user in userRatings):
            userRatings[user].append(rating)
        else:
            userRatings[user] = [rating]

userAverageRating = {}
for user, ratings in userRatings.items():
    userAverageRating[user] = sum(ratings)/len(ratings)

bUu = {}

for user, averageRating in userAverageRating.items():
    bUu[user] = averageRating-r_average

In [ ]:
test = list(set(zip(m, r)))
test.sort()
movieRatings = {}

for movie, rating in test:
    if(rating!= None):
        if(movie in movieRatings):
            movieRatings[movie].append(rating)
        else:
            movieRatings[movie] = [rating]
movieAverageRating = {}
for movie, ratings in movieRatings.items():
    movieAverageRating[movie] = sum(ratings)/len(ratings)

bMm = {}
for movie, averageRating in movieAverageRating.items():
    bMm[movie] = averageRating-r_average


In [84]:
test = list(set(zip(u, m)))
rum = {}

for u, m in test:
    rum[(u,m)] = r_average + bUu[u] + bMm[m]

rum

{(1025, 1074): 2.4001538967664953,
 (629, 1074): 2.4001538967664953,
 (155, 437): 2.4001538967664953,
 (683, 556): 2.9001538967664953,
 (779, 1018): 2.9001538967664953,
 (1605, 602): 2.4001538967664953,
 (1954, 756): 2.9001538967664953,
 (923, 16): 2.4001538967664953,
 (1893, 480): 2.4001538967664953,
 (391, 155): 2.4001538967664953,
 (1461, 823): 2.4001538967664953,
 (401, 843): 2.4001538967664953,
 (62, 1377): 2.4001538967664953,
 (523, 274): 2.4001538967664953,
 (1174, 766): 2.4001538967664953,
 (637, 561): 2.4001538967664953,
 (1905, 490): 2.4001538967664953,
 (1605, 952): 2.4001538967664953,
 (447, 437): 2.4001538967664953,
 (946, 1316): 3.4001538967664953,
 (345, 160): 2.4001538967664953,
 (735, 315): 2.9001538967664953,
 (1967, 587): 2.9001538967664953,
 (1232, 1121): 2.4001538967664953,
 (1870, 654): 2.4001538967664953,
 (1596, 85): 2.4001538967664953,
 (166, 1326): 2.4001538967664953,
 (930, 32): 2.4001538967664953,
 (1028, 567): 2.6501538967664953,
 (1812, 649): 2.40015389676